name:        pi-base-server
version:     '0.0.2'
homepage:    http://github.com/pi-base/server
bug-reports: http://github.com/pi-base/server/issues
author:      James Dabbs
maintainer:  jamesdabbs@gmail.com
copyright:   2018 James Dabbs
license:     MIT
github:      pi-base/server
default-extensions:
  - CPP
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - TypeFamilies
dependencies:
  - containers
  - protolude
  - text
library:
  source-dirs:
    - src
    - app
  dependencies:
    - base
    - aeson
    - aeson-pretty
    - ansi-terminal
    - attoparsec
    - bytestring
    - case-insensitive
    - classy-prelude
    - classy-prelude-conduit
    - classy-prelude-yesod
    - conduit
    - conduit-combinators
    - conduit-extra
    - cryptohash
    - data-default
    - directory
    - either
    - esqueleto
    - exceptions
    - fast-logger
    - file-embed
    - filepath
    - foreign-store
    - github-webhook-handler
    - gitlib
    - gitlib-libgit2
    - gitrev
    - graphql-api
    - hjsmin
    - http-conduit
    - http-types
    - lens
    - lens-aeson
    - lifted-base
    - load-env
    - monad-control
    - monad-logger
    - mtl
    - persistent
    - persistent-postgresql
    - persistent-template
    - safe
    - scientific
    - shakespeare
    - shelly
    - tagged
    - template-haskell
    - time
    - transformers
    - unix
    - unliftio
    - unordered-containers
    - uuid
    - vector
    - wai
    - wai-cors
    - wai-extra
    - wai-logger
    - warp
    - wreq
    - yaml
    - yesod
    - yesod-auth
    - yesod-auth-oauth2
    - yesod-core
    - yesod-form
    - yesod-static
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2
executables:
  pibase:
    main: cli.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - pi-base-server
    - foreign-store
    - warp
    - directory
    - fast-logger
    - filepath
    - optparse-applicative
    - persistent-postgresql
    - shelly
    when:
    - condition: flag(library-only)
      buildable: false
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
    dependencies:
    - base
    - pi-base-server
    - aeson
    - aeson-pretty
    - aeson-qq
    - bytestring
    - classy-prelude
    - classy-prelude-yesod
    - containers
    - conduit
    - conduit-combinators
    - exceptions
    - gitlib
    - gitlib-libgit2
    - hspec
    - hspec-core
    - http-types
    - HUnit
    - lens
    - lens-aeson
    - monad-logger
    - persistent
    - persistent-postgresql
    - pretty-show
    - QuickCheck
    - resourcet
    - shakespeare
    - tasty
    - tasty-hspec
    - template-haskell
    - transformers
    - unliftio-core
    - unliftio
    - unordered-containers
    - wai-extra
    - yesod
    - yesod-auth
    - yesod-core
    - yesod-test
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
