name:        pi-base-server
version:     '0.0.2'
homepage:    http://github.com/pi-base/server
bug-reports: http://github.com/pi-base/server/issues
author:      James Dabbs
maintainer:  jamesdabbs@gmail.com
copyright:   2018 James Dabbs
license:     MIT
github:      pi-base/server
default-extensions:
  - ConstraintKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - StandaloneDeriving
  - TypeFamilies
dependencies:
  - aeson
  - bytestring
  - containers
  - exceptions
  - gitlib
  - gitlib-libgit2
  - lens
  - lens-aeson
  - monad-logger
  - persistent
  - persistent-postgresql
  - protolude
  - text
  - time
  - transformers
  - unliftio
  - wai
library:
  source-dirs:
    - src
  dependencies:
    - base
    - attoparsec
    - aeson-pretty
    - conduit
    - cookie
    - data-default
    - deepseq
    - directory
    - either
    - esqueleto
    - fast-logger
    - filepath
    - gitrev
    - graphql-api
    - http-types
    - monad-control
    - mtl
    - persistent-template
    - scientific
    - servant-server
    - shelly
    - tagged
    - template-haskell
    - unix
    - unordered-containers
    - uuid
    - vault
    - vector
    - wai-cors
    - wai-session
    - warp
    - wreq
    - yaml
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2
executables:
  pibase:
    main: cli.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - base
    - pi-base-server
    - load-env
    - optparse-applicative
    - shelly
    when:
    - condition: flag(library-only)
      buildable: false
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    default-extensions:
    - QuasiQuotes
    dependencies:
    - base
    - pi-base-server
    - ansi-terminal
    - aeson-qq
    - attoparsec
    - case-insensitive
    - fast-logger
    - hspec
    - hspec-core
    - hspec-wai
    - http-types
    - QuickCheck
    - tasty
    - tasty-hspec
    - template-haskell
    - unordered-containers
    - wai-extra
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
