name:        pi-base-server
version:     '0.0.2'
homepage:    http://github.com/pi-base/server
bug-reports: http://github.com/pi-base/server/issues
author:      James Dabbs
maintainer:  jamesdabbs@gmail.com
copyright:   2018 James Dabbs
license:     MIT
github:      pi-base/server
default-extensions:
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
dependencies:
  - aeson
  - bytestring
  - containers
  - exceptions
  - lens
  - lens-aeson
  - monad-logger
  - mtl
  - persistent
  - polysemy
  - polysemy-plugin
  - protolude
  - template-haskell
  - text
  - time
  - unordered-containers
  - warp
ghc-options:
- -Wall
- -fmax-relevant-binds=0
- -fmax-valid-hole-fits=1
- -flate-specialise
- -fspecialise-aggressively
- -fplugin=Polysemy.Plugin
# - -fno-warn-deprecations
# - -Werror
library:
  source-dirs:
    - src
  dependencies:
    - base
    - attoparsec
    - beam-core
    - conduit
    - gitlib
    - gitlib-libgit2
    - gitrev
    - http-client
    - http-types
    - persistent-postgresql
    - persistent-template
    - reason-export
    - servant-client
    - servant-client-core
    - servant-foreign
    - servant-reason
    - servant-server
    - tagged
    - uuid
    - wreq
    - yaml
    - wai
    - wai-extra
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2
      - -fno-warn-deprecations
executables:
  pibase:
    main: main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - base
    - pi-base-server
    - load-env
    - optparse-applicative
    - uuid
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -fno-warn-deprecations
    default-extensions:
    - QuasiQuotes
    dependencies:
    - base
    - pi-base-server
    - aeson-qq
    - hspec
    - persistent-postgresql
    - QuickCheck
    - raw-strings-qq
    - tasty
    - tasty-hspec
    - temporary
    - uuid
