# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-12.18

packages:
- '.'
- location:
#     git: https://github.com/haskell-graphql/graphql-api.git
#     commit: f06c7af1bc0c9e475f88e47448218373eb9686b6
    git: https://github.com/jamesdabbs/graphql-api.git
    commit: e02923deffd14ad2685bd4d68c4ba9edbb06e250
  extra-dep: true
- location:
    git: https://github.com/bitemyapp/esqueleto.git
    commit: b81e0d951e510ebffca03c5a58658ad884cc6fbd
  extra-dep: true
- location:
    git: https://github.com/jwiegley/gitlib.git
    commit: 0463bcedf3ef37d0bf61b432c350ddf5c20089fd
  subdirs:
    - gitlib-libgit2
  extra-dep: true

extra-deps:
- gitlib-3.1.2

allow-newer: false

flags: {}

extra-package-dbs: []

extra-include-dirs:
- /usr/local/opt/icu4c/include
extra-lib-dirs:
- /usr/local/opt/icu4c/lib

docker:
  enable: false
  mount:
    - '/data/src/pi-base/server/env/dev:/app/env'
    - '/data/src/pi-base/data:/data'
    - '/data/src/pi-base/gitlib:/data/src/pi-base/gitlib'
    - '/data/src/pi-base/graphql-api:/data/src/pi-base/graphql-api'

image:
  container:
    base: 'pibase/base:latest'
    name: 'pibase/server'
    add:
      config: /app/config
      static: /app/static
    executables:
      - 'pi-base-server'
