# For advanced use and comprehensive documentation of the format, please see:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-8.24

packages:
- '.'
- location:
    git: https://github.com/jamesdabbs/github.git
    commit: 73d154837d354810f7b374f556e81ca0c9728a65
  extra-dep: true
# - '/data/src/pi-base/gitlib/gitlib-libgit2'
- location:
    git: https://github.com/jamesdabbs/gitlib.git
    commit: 1abcd2d90131b03f7d9fb5b46545ab96e2b22199
  subdirs:
    - gitlib-libgit2
  extra-dep: true
- location:
    git: https://github.com/thoughtbot/yesod-auth-oauth2.git
    commit: 25e63cdcc22935aed3dde79ef9f233ff783eeea3
  extra-dep: true
# - '/data/src/pi-base/graphql-api'
- location:
    git: https://github.com/jml/graphql-api.git
    commit: ba407bc8aaa182aa3e98ca0cdce509231e2318ca
  extra-dep: true

extra-deps:
- lens-aeson-1.0.1
- load-env-0.1.1

flags: {}

extra-package-dbs: []

extra-include-dirs:
- /usr/local/opt/icu4c/include
extra-lib-dirs:
- /usr/local/opt/icu4c/lib

docker:
  enable: true
  mount:
    - '/data/src/pi-base/server/env/dev:/app/env'
    - '/data/src/pi-base/data:/data'
    - '/data/src/pi-base/gitlib:/data/src/pi-base/gitlib'
    - '/data/src/pi-base/graphql-api:/data/src/pi-base/graphql-api'

image:
  container:
    base: 'pibase/base:latest'
    name: 'pibase/server'
    add:
      config: /app/config
      static: /app/static
    executables:
      - 'pi-base-server'
