query Viewer($version: String) {
  viewer(version: $version) {
    version
    spaces {
      __typename
      uid
      name
      references { 
        # TODO: these should be fragments
        __typename
        type
        ref
        name
      }
      description
      traits {
        __typename
        property {
          __typename
          uid
        }
        value
        description
        deduced
        references {
          __typename
          type
          ref
          name
        }
      }
    }
    properties {
      __typename
      uid
      name
      references {
        __typename
        type
        ref
        name
      }
      description
    }
    theorems {
      __typename
      uid
      if
      then
      references {
        __typename
        type
        ref
        name
      }
      description
    }
  }
}