# TODO: cache stack, node build dependencies
version: 2
jobs:
  build_server:
    docker:
      - image: quay.io/jamesdabbs/pibase:ci
    steps:
      - checkout
      - run:
          name: Build binary
          command: |
            stack build --pedantic
            mkdir -p /tmp/workspace/server/bin
            cp -r $(stack path --local-install-root)/bin config static /tmp/workspace/server
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - server

  build_viewer:
    docker:
      - image: circleci/node:10.11
    steps:
      - checkout
      - run:
          name: Build bundle
          command: |
            cd viewer
            yarn install
            yarn run build
            mkdir /tmp/workspace
            cp -r build /tmp/workspace/viewer
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - viewer

  test_server:
    docker:
      - image: quay.io/jamesdabbs/pibase:ci
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: pi_base_test
    environment:
      CI:        true
      REPO_PATH: /data/repo
    steps:
      - checkout
      - run:
          name: Clone data repo
          command: |
            git clone --bare https://github.com/pi-base/data.git /data/repo/.git
      - run:
          name: Run tests
          command: stack test --fast --no-terminal

  test_viewer:
    docker:
      - image: circleci/node:10.11
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run tests
          command: |
            cd viewer
            yarn install
            yarn test

  release:
    docker:
      - image: quay.io/jamesdabbs/pibase:ci
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Upload to S3
          command: |
            aws s3 sync --region us-east-2 --delete /tmp/workshop/server s3://pi-base/deploy/server
            aws s3 sync --region us-east-2 --acl public-read --delete /tmp/workshop/viewer s3://topology.pi-base.org

workflows:
  version: 2
  release:
    jobs:
      - build_server
      - build_viewer
      - test_server
      - test_frontend:
          requires:
            - build_server
            - build_viewer
            - test_server
      - release:
          requires:
            - test_frontend
