version: 2
jobs:
  build_server:
    docker:
      - image: quay.io/jamesdabbs/pibase:ci
    steps:
      - checkout
      - run:
          name: Build binary
          command: |
            stack build --pedantic
            mkdir -p /tmp/workspace/server
            cp $(stack path --local-install-root)/bin/pibase /tmp/workspace/server
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - server

  build_viewer:
    docker:
      - image: quay.io/jamesdabbs/pibase:ci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "viewer/package.json" }}
            - v1-npm-
      - run:
          name: Build bundle
          command: |
            cd viewer
            yarn install
            yarn run build
            mkdir /tmp/workspace
            cp -r build /tmp/workspace/viewer
      - save_cache:
          key: v1-npm-{{ checksum "viewer/package.json" }}
          paths:
            - ~/viewer/node_modules
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - viewer

  test_server:
    docker:
      - image: quay.io/jamesdabbs/pibase:ci
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: pi_base_test
    environment:
      CI:            true
      REPO_PATH:     /data/repo
      REPO_UPSTREAM: /data/upstream
    steps:
      - checkout
      - run:
          name: Clone data repo
          command: |
            git clone --bare https://github.com/pi-base/test-data.git /data/upstream/.git
      # TODO: compile and publish coverage metrics
      - run:
          name: Run tests
          command: stack test --fast --no-terminal

  test_viewer:
    docker:
      - image: quay.io/jamesdabbs/pibase:ci
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: pi_base_development
    environment:
      GITHUB_TOKEN: xxx
      GITHUB_CLIENT_ID: xxx
      GITHUB_CLIENT_SECRET: xxx
      GITHUB_CALLBACK_URI: xxx
      GITHUB_WEBHOOK_SECRET: xxx
      SERVER_BIN_PATH: /tmp/workspace/server/pibase
      SERVER_TRACING: true
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "viewer/package.json" }}
            - v1-npm-
      - run:
          name: Run tests
          command: |
            cd viewer
            yarn install
            yarn run schema
            yarn test

  release:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Upload to S3
          command: |
            aws s3 sync --region us-east-2 /tmp/workspace/server s3://pi-base/deploy/$CIRCLE_BUILD_NUM/server
            aws s3 sync --region us-east-2 /tmp/workspace/viewer s3://pi-base/deploy/$CIRCLE_BUILD_NUM/viewer

workflows:
  version: 2
  release:
    jobs:
      - build_server
      - build_viewer
      - test_server
      - test_viewer:
          requires:
            - build_server
            - build_viewer
            - test_server
      - release:
          requires:
            - test_viewer
