version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build
    environment:
      CI:        true
      REPO_PATH: /data/repo
    steps:
      - checkout
      - run:
          name: Clone data repo
          command: |
            git clone --mirror https://github.com/pi-base/data.git /data/repo/.git
            cd /data/repo
            git config --bool core.bare false
            git checkout master

      # Build and cache installed dependencies based on package.yml
      - restore_cache:
          keys:
            - v1-stack-deps-{{ checksum "package.yaml" }}
            - v1-stack-deps-
      - run:
          name: Build deps
          command: stack build --only-dependencies
      - run:
          name: Build test deps
          command: stack build --test --only-dependencies
      - save_cache:
          key: v1-stack-deps-{{ checksum "package.yaml" }}
          paths: 
            - ~/.stack
            - .stack-work

      # Run the tests
      - run:
          name: Run tests
          command: stack test --coverage

      # Build the binary as an artifact
      - run:
          name: Build binary
          command: stack build && mkdir /tmp/artifacts && cp $(stack path --local-install-root)/bin/pi-base-server /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts