apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pi-base-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: pibase/server:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            
