# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
ip-from-header: "_env:IP_FROM_HEADER:false"

frontend-url: "_env:VIEWER_REDIRECT_URL:http://localhost:3000"

github-owner: "_env:GITHUB_OWNER:pi-base"
github-repo:  "_env:GITHUB_REPO:data"

# Path to a copy of the pi-base/data repo on the local machine
repo-path:      "_env:REPO_PATH:/data/repo"
default-branch: "_env:DEFAULT_BRANCH:master"
auto-push:      "_env:AUTO_PUSH:false"

# Authorization to use for the webhook validator
github-auth:           "_env:GITHUB_AUTH:"
github-webhook-secret: "_env:GITHUB_WEBHOOK_SECRET:"

# OAuth app credentials for signing in with Github
github-client-id:     "_env:GITHUB_CLIENT_ID:"
github-client-secret: "_env:GITHUB_CLIENT_SECRET:"

test-mode: "_env:TEST_MODE:false"

# Default behavior: determine the application root from the request headers.
# Uncomment to set an explicit approot
approot: "_env:APPROOT:http://localhost:3141"

log-level: "_env:LOG_LEVEL:error"

rollbar-token: "_env:ROLLBAR_TOKEN"
rollbar-environment: "_env:ROLLBAR_ENVIRONMENT:production"
rollbar-host: "_env:ROLLBAR_HOST:unknown"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false
# auth-dummy-login : false

# NB: If you need a numeric value (e.g. 123) to parse as a String, wrap it in single quotes (e.g. "_env:PGPASS:'123'")
# See https://github.com/yesodweb/yesod/wiki/Configuration#parsing-numeric-values-as-strings

database:
  # See config/test-settings.yml for an override during tests
  database: "_env:SQLITE_DATABASE:/data/pi-base-server.sqlite3"
  poolsize: "_env:SQLITE_POOLSIZE:10"

copyright: Insert copyright statement here
#analytics: UA-YOURCODE
