# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
ip-from-header: "_env:IP_FROM_HEADER:false"

compile-queries: "_env:COMPILE_QUERIES:false"
error-token:     "_env:ERROR_TOKEN:xxx"
frontend-url:    "_env:VIEWER_REDIRECT_URL:http://localhost:3000"
log-level:       "_env:LOG_LEVEL:error"
test-mode:       "_env:TEST_MODE:false"

repo:
  path:           "_env:REPO_PATH:xxx"
  default-branch: "_env:REPO_DEFAULT_BRANCH:master"
  auto-push:      "_env:REPO_AUTO_PUSH:false"
  upstream:       "_env:REPO_UPSTREAM:git@github.com:pi-base/data.git"
  downstream:     "_env:REPO_DOWNSTREAM:xxx"

github:
  token:          "_env:GITHUB_TOKEN:xxx"
  owner:          "_env:GITHUB_OWNER:pi-base"
  repo:           "_env:GITHUB_REPO:data"
  client-id:      "_env:GITHUB_CLIENT_ID:xxx"
  client-secret:  "_env:GITHUB_CLIENT_SECRET:xxx"
  webhook-secret: "_env:GITHUB_WEBHOOK_SECRET:xxx"

rollbar:
  token:       "_env:ROLLBAR_TOKEN"
  environment: "_env:ROLLBAR_ENVIRONMENT:production"
  host:        "_env:ROLLBAR_HOST:unknown"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false
# auth-dummy-login : false

# NB: If you need a numeric value (e.g. 123) to parse as a String, wrap it in single quotes (e.g. "_env:PGPASS:'123'")
# See https://github.com/yesodweb/yesod/wiki/Configuration#parsing-numeric-values-as-strings

database:
  # See config/test-settings.yml for an override during tests
  database: "_env:DATABASE_NAME:pi_base_development"
  poolsize: "_env:DATABASE_POOL_SIZE:10"
  host:     "_env:DATABASE_HOST:localhost"
  user:     "_env:DATABASE_USER:"
  password: "_env:DATABASE_PASSWORD:"

copyright: Insert copyright statement here
#analytics: UA-YOURCODE
