log-level: error

repo:
  path: tmp/repo/working.git
  default-branch: master
  auto-push: true
  upstream: tmp/repo/origin.git

rollbar:
  environment: test

database:
  database: pi_base_test
  poolsize: 5
  host:     localhost

log-requests: false
