log-level: error

repo:
  path: /tmp/pi-base-test-repo.git
  default-branch: master
  auto-push: true
  upstream: https://github.com/pi-base/data.git
  downstream: /tmp/pi-base-test-downstream.git

rollbar:
  environment: test

database:
  database: pi_base_test
  poolsize: 5
  host:     localhost

log-requests: false
